# Generated by Django 4.2.1 on 2023-05-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Registrations", "0002_app_mobility_services"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="app_mobility_services", new_name="app_mobility_services_models",
        ),
    ]
